# Generated by Django 6.0.6 on 2026-07-10 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='report',
            options={'ordering': ['-created_at']},
        ),
        migrations.RenameField(
            model_name='report',
            old_name='message',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='report',
            old_name='reporter_name',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='report',
            name='category',
            field=models.CharField(choices=[('Complaint', 'Complaint'), ('Suggestion', 'Suggestion'), ('School Issue', 'School Issue'), ('Teacher Issue', 'Teacher Issue'), ('Infrastructure', 'Infrastructure'), ('Other', 'Other')], max_length=50),
        ),
        migrations.AlterField(
            model_name='report',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Reviewed', 'Reviewed'), ('Resolved', 'Resolved')], default='Pending', max_length=20),
        ),
    ]
